# -*- coding: utf-8 -*-
"""Idea_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSi7ALpxHI-_7elwzsgr5SPwp_n_tz6x
"""

#install deps
!pip install -q transformers gradio torch accelerate

#import and load model
from transformers import pipeline
import gradio as gr

#use better instruction tuned model
generator=pipeline(
    "text2text-generation",
    model="MBZUAI/LaMini-Flan-T5-783M",
    device_map="auto"
)

#function
def generate_idea(domain):
  if not domain or not domain.strip():
    return "Please provide a domain (e.g fintech,agritech)"
  prompt =f"""
Generate a startup pitch for the domain{domain}.
Include the following sections:

1) Business Idea (2-3 sentences)
2) problem statement (explain the challeneg clearly)
3) solution (explain how the startup solves it)
"""
  result = generator(
     prompt,
     max_new_tokens=400, # Corrected typo here
     temperature=0.8,
     do_sample=True
 )
  generated_text = result[0]["generated_text"]
  if not generated_text or not generated_text.strip():
      return "Could not generate a startup idea for this domain. Please try another one."
  return generated_text

#Gradio UI
demo =gr.Interface(
    fn=generate_idea,
    inputs=gr.Textbox(label="Domain of Interest",placeholder="e.g agritech"),
    outputs="text",
    title="Startup Idea + Pitch Generator",
    description="Enter a domain (e.g fintech,agritech) and get a startup pitch with Problem and Solution."
)
demo.launch(share=True)